### ISSUE TITLE
Discord Invite Link Invalid

### ISSUE THREAD

**Issue by Geoff12889** [ENIACElec/FlexbarDesignerPreview#1]
Join our Discord community: https://discord.gg/ws2tE92N

Trying to join the discord server. The link from the main page says that the invite link is invalid (most likely expired). Could you update the link, or indevidually invite me. I can send you my discord username if needed.

Pledged on Kickstarter for 2x Flexbars. Looking forward to adding this to my workflow!

Thanks!

**Comment by ENIACElec** [comment]
----------Reply to Message----------
 On Wed, Dec 18, 2024 22:33 PM Geoffrey ***@***.***&gt; wrote:

  

 
Join our Discord community: https://discord.gg/ws2tE92N
 
Trying to join the discord server. The link from the main page says that the invite link is invalid (most likely expired). Could you update the link, or indevidually invite me. I can send you my discord username if needed.
 
Pledged on Kickstarter for 2x Flexbars. Looking forward to adding this to my workflow!
 
Thanks!

**Comment by Geoff12889** [comment]
Hey there! It looks like you tried to reply to my post but it only looks like you quoted my original post.

**Comment by ENIACElec** [comment]
Hi Woytt!
Sorry for the inconvenience; that email app is too cumbersome.
Please join the Discord via this link.&nbsp;
https://discord.gg/7STSjmBpKT
Best,
Aspen
&nbsp;
&nbsp;
------------------&nbsp;Original&nbsp;------------------
From: ***@***.***&gt;;
Date: &nbsp;Fri, Dec 20, 2024 09:55 PM
To: ***@***.***&gt;; 
Cc: ***@***.***&gt;; ***@***.***&gt;; 
Subject: &nbsp;Re: [ENIACElec/FlexbarDesignerPreview] Discord Invite Link Invalid (Issue #1)

&nbsp;



 
Hey there! It looks like you tried to reply to my post but it only looks like you quoted my original post.

**Comment by Geoff12889** [comment]
Updated link worked. Thanks!
